// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fitkxkahoxljhttndemg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpdGt4a2Fob3hsamh0dG5kZW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDcxNzQsImV4cCI6MjA3MzkyMzE3NH0.tTzy_A4rY04puj0N2fMwVvE6BwYXNUFlLsNPH372KRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});